@extends('layout.basic')
@section('content')
<section id="service" class="home-section">

<h2><b>TERMS OF SERVICE</b></h2>

<p>PLEASE READ THESE TERMS OF USE (“AGREEMENT”) CAREFULLY BEFORE USING THE SERVICES OFFERED BY TOPOINT, LLC. (“COMPANY” OR “WE” OR “US”). THIS IS A BINDING AGREEMENT BETWEEN YOU AND COMPANY. BY VISITING THE WEBSITES OR USING THE SERVICES IN ANY MANNER, YOU AGREE THAT YOU HAVE READ AND AGREE TO BE BOUND BY AND A PARTY TO THE TERMS AND CONDITIONS OF THIS AGREEMENT TO THE EXCLUSION OF ALL OTHER TERMS. IF THE TERMS OF THIS AGREEMENT ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. IF YOU DO NOT UNCONDITIONALLY AGREE TO ALL THE TERMS AND CONDITIONS OF THE AGREEMENT, YOU HAVE NO RIGHT TO USE THE WEBSITE OR SERVICES. USE OF COMPANY’S SERVICES IS EXPRESSLY CONDITIONED UPON YOUR ASSENT TO ALL THE TERMS AND CONDITIONS OF THIS AGREEMENT, TO THE EXCLUSION OF ALL OTHER TERMS.</p>

<h2><b>USE OF THE SERVICES</b></h2>

<p>Welcome to <b>teachtogether.co</b>, a service brought to you by topoint, LLC. Please continue reading to learn about the rules and restrictions that govern use of the <b>teachtogether.co</b> website and all other websites affiliated with Company, and any other linked pages, features, or content (collectively, the “Website”) and the service available on SMS and any other products, services and applications offered from time to time by Company (collectively, with the Website, the “Services”). The term “Services” will include, without limitation, any service Company performs for you and the content offered by Company on the Website or any application.
You represent and warrant to Company that: (i) you are an individual (i.e., not a corporation) and you are of legal age to form a binding contract (or, if you are a minor, you have your parent's or legal guardian’s permission to use the Services, and that your parent or legal guardian has read and agrees to this Agreement on your behalf); (iii) you will maintain the accuracy of such information; (iv) if you are accepting this Agreement on behalf of an institution, company or other legal entity, you have the authority to bind that institution, company or legal entity to this Agreement. If you are accepting this Agreement on behalf of an institution, company or legal entity: (i) “you” includes you and that legal entity, and (ii) to the extent your legal entity has a separate written agreement with Company, that agreement will define the order of precedence between this Agreement and that separate agreement with respect to such entity, provided that you remain individually bound by these terms with respect to your use of the Services. You also certify that you are legally permitted to use and access the Services, and that you have the right to provide to the Company any and all information and materials you submit to the Service, and you take full responsibility for the selection and use of and access to the Services. This Agreement is void where prohibited by law, and the right to access the Services is revoked in such jurisdictions.
For information regarding Company's collection, storage, use, and disclosure of personally identifiable information, please review Company's current Privacy Policy, available at <a href="http://teachtogether.co/privacy">http://teachtogether.co/privacy</a> which is hereby incorporated into this Agreement by reference.</p>

<h2><b>CHANGE TO THESE TERMS</b></h2>

<p>We are constantly trying to improve our Services, so this Agreement may need to change along with the Services. We reserve the right to modify this Agreement at any time, but we will do our best to bring this to your attention by posting a notice on the Website or in our applications, or by sending you a notice via email. You will be responsible for reviewing and becoming familiar with any such modifications. Your use of the Services or the Website following such notification constitutes your acceptance of the terms and conditions of this Agreement as modified.</p>

<h2><b>USE BY CHILDREN</b></h2>

<p>Because some of our users may be interested in it, we have included some information below related to the Children’s Online Privacy and Protection Act (“COPPA”). COPPA requires that online service providers obtain parental consent, with limited exceptions, before they knowingly collect personally identifiable information online from children who are under 13. We do not knowingly collect or solicit personally identifiable information from a child under 13. If we learn we have collected personal information from a student under 13, except for that child’s name, and child’s parent’s email address, without parental consent being obtained from his or her parent or guardian, or if we learn a student under 13 has provided us personal information beyond what we request from him or her, we will delete that information as quickly as possible. If you believe that a student under 13 may have provided us personal information in violation of this paragraph, please contact us at <a href="mailto:teachtogether1@gmail.com">teachtogether1@gmail.com.</a></p>

<h2><b>RESPONSIBILITY FOR FEES AND USAGE CHARGES</b></h2>

<p>By using the Service, you may receive e-mail or text messages on your phone or mobile communications device, and the receipt of such messages may cause you to incur usage charges or other fees or costs in accordance with your wireless or data service plan. Any and all such charges, fees, or costs are your sole responsibility. You should consult with your wireless carrier to determine what rates, charges, fees, or costs may apply to your use of the Services.</p>

<h2><b>TERMS REGARDING REGISTRATION</b></h2>

<p>A. FERPA. Certain information that may be provided to Company by teachers and other users, such as student directory information and performance metrics, may be considered an educational record (“Education Record”) under the Family Educational Rights and Privacy Act (“FERPA”). If you are a parent, you hereby authorize and consent to Company storing and accessing such Education Records, and if you are a teacher, you represent that you or your school or district has obtained all necessary consents to share such Educational Records with Company, in each case, solely to enable Company’s operation of the Services from your parent, legal guardian, or other person authorized to provide such permission.</p>

<p>B. Social Media. Company may, now or in the future, incorporate certain functions that allow you to interact with the Service through your accounts on certain supported third party services, such as social networks or network storage sites (“Linked Accounts”), such as with “Like” and “Share” buttons, or similar features. If you choose to use such features, you grant Company permission to access and use your Linked Account for the purpose of processing your requests.</p>

<h2><b>CONSENT TO RECEIVE PERIODIC MESSAGES FROM TOPOINT</b></h2>

<p>As part of the Services, the Company sometimes causes administrative messages to be sent to members of a class group. For example, upon adding a new member to a class group, such new member will receive a welcome message, instructions on how to stop receiving messages, and information on how to avoid certain charges by downloading the topoint Application or visiting the official website. The Company also may inform group members who have not replied that they automatically will be removed from the class group if they do not participate. The Company may send other administrative messages as well. BY SIGNING UP FOR THE SERVICE, YOU AGREE TO RECEIVE TEXT MESSAGES, AND YOU REPRESENT AND WARRANT THAT EACH PERSON YOU ADD TO A GROUP HAS CONSENTED TO RECEIVE TEXT MESSAGES.</p>

<h2><b>CONTENT</b></h2>

<p>a) The Services and the contents of the Website, and all the software and technology used in the provision of the Services are intended solely for the personal, non-commercial use of Website users and may only be used in accordance with the terms of this Agreement. All such software and technology, and materials displayed or performed on the Website (including, but not limited to text, graphics, articles, photographs, images, illustrations (also known as the "Content") are protected by copyright and other intellectual property laws. You shall abide by all copyright notices, trademark rules, information, and restrictions contained in any Content accessed through the Services, and shall not use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purposes whatsoever any Content or third party submissions or other proprietary rights not owned by you: (i) without the express prior written consent of the respective owners, and (ii) in any way that violates any third party right.</p>

<p>b) The Website is protected by copyright as a collective work and/or compilation, pursuant to U.S. copyright laws, international conventions, and other copyright laws. You may not modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section 4), create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.</p>

<p>c) You may download a single copy of the Content (and other items displayed on the Website for download) for personal non-commercial use only, provided that you maintain all copyright and other notices contained in such Content. You shall not store any significant portion of any Content in any form. Copying or storing of any Content other than personal, noncommercial use is expressly prohibited without prior written permission from Company or from the copyright holder identified in such Content's copyright notice. You shall not link to the Website without Company's prior written consent, except in accordance with the terms of this Agreement.</p>

<p>d) In the course of using the Services, you and other users may provide information which may be used by Company in connection with the Services and which may be visible to certain other users. You understand that by posting information or content on the Website or otherwise providing content, materials or information to Company or in connection with the Services (collectively, "User Submissions"), and you hereby grant to Company and its successors a non-exclusive, worldwide, royalty free, and transferable right and license (without obligation) to reproduce, distribute, publicly perform and display, and modify such User Submissions (including all related intellectual property rights) and to allow others to do so as may be reasonably necessary to provide the Services to you and other users; however, Company will only share your personally identifiable information in accordance with Company's current privacy policy at <a href="http://www.teachtogether.co/privacy">.http://www.teachtogether.co/privacy.</a> You also hereby do and shall grant each user of the Services a non-exclusive license to access your User Submissions through the Services, and to use, modify, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Services and under this Agreement. Furthermore, you understand that Company retains the right to reformat, modify, create derivative works of, excerpt, and translate any User Submissions submitted by you. You understand that all information publicly posted or privately transmitted through the Services is the sole responsibility of the person from which such content originated and that Company will not be liable for any errors or omissions in any content. You understand that Company cannot guarantee the identity of any other users with whom you may interact in the course of using the Services. Additionally, Company cannot guarantee the authenticity of any data, which users may provide about themselves. You acknowledge that all Content accessed by you using the Services is at your own risk and you will be solely responsible for any damage or loss to any party resulting therefrom. Company does not guarantee that it will publish any of your User Submissions, and reserves the right to remove User Submissions from the Service at any time for any reason, including without limitation in connection with reports that such User Submissions infringe third party intellectual property rights.</p>

<p>e) Under no circumstances will Company be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred in connection with use of or exposure to any Content posted, emailed, accessed, transmitted, or otherwise made available via the Services.</p>

<h2><b>YOUR WARRANTY</b></h2>

<p>You warrant, represent and agree that you will not contribute any Content or otherwise use the Services in a manner that (i) infringes or violates the intellectual property rights or proprietary rights, rights of publicity or privacy, or other rights of any third party; (ii) violates any law, statute, ordinance or regulation; (iii) is harmful, fraudulent, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, or otherwise objectionable; or (iv) jeopardizes the security of your account in any way, such as allowing someone else access to your account or password. Company reserves the right to remove any Content from the Services at any time, for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if Company is concerned that you may have breached the immediately preceding sentence), or for no reason at all. You, not Company, remain solely responsible for all Content that you upload, post, email, transmit, or otherwise disseminate using, or in connection with, the Services, and you warrant that you possess all rights necessary to provide such content to Company and to grant Company the rights to use such information in connection with the Services and as otherwise provided herein.</p>

<h2><b>RESTRICTIONS AND RESPONSIBILITIES</b></h2>

<p>The Company has no special relationship or fiduciary duty to you. You are responsible for all of your activity in connection with the Services. You agree that you will use the Services in compliance with all applicable local, state, national, and international laws, rules and regulations, including any laws regarding the transmission of technical data exported from your country of residence. You will not, will not agree to, and will not authorize or encourage any third party to: (i) use the Services to upload, transmit or otherwise distribute any content that is unlawful, defamatory, harassing, abusive, fraudulent, obscene, contains viruses, Trojan horses, worms, time bombs, malware, or otherwise harmful computer code, or is otherwise objectionable as reasonably determined by <b>topoint, LLC</b>; (ii) upload, transmit or otherwise distribute content that infringes upon another party’s intellectual property rights or other proprietary, contractual or fiduciary rights or obligations; (iii) prevent others from using the Services in a manner consistent with this Agreement; (iv) use the Services for any unlawful, fraudulent or inappropriate purpose, including, without limitation, to obtain the password, account, or private information from any user or to violate the security of any computer network, crack passwords or security encryption codes or engage in any kind of illegal activity; (v) decompile, reverse engineer, or otherwise attempt to obtain the source code of the Services; (vi) use manual or automated software, devices, or other processes to “crawl,” “scrape,” or “spider” any portion of the Services, or (vii) run Maillist, Listserv, any form of auto-responder, or “spam” on the Services, or any processes that run or are activated while you are not logged on to the Services, or that otherwise interfere with the proper working of or place an unreasonable load on the Services’ infrastructure. You will be responsible for withholding, filing, and reporting all taxes, duties and other governmental assessments associated with your activity in connection with the Services. You may not transfer your account to anyone without express prior written consent of Company. Violation of any of the foregoing may result in immediate termination of your account, revocation of your ability to use the Services, and may subject you to state and federal penalties and other legal consequences. <b>Topoint, LLC</b> reserves the right, but will have no obligation, to investigate your use of the Services in order to determine whether a violation of the Agreement has occurred or to comply with any applicable law, regulation, legal process or governmental request.
You will be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access, or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. You will be responsible for ensuring that such equipment or ancillary services are compatible with the Services.</p>

<h2><b>WARRANTY AND DISCLAIMER</b></h2>

<p>Company has no special relationship with or fiduciary duty to you. You acknowledge that Company has no control over, and no duty to take any action regarding: which users gains access to the Services; what Content you accesses via the Services; what effects the Content may have on you; how you may interpret or use the Content; or what actions you may take as a result of having been exposed to the Content. You release Company from all liability for you having acquired or not acquired Content through the Services. The Services may contain, or direct you to websites containing, information that some people may find offensive or inappropriate. Company makes no representations concerning any content contained in or accessed through the Services, and Company will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Services. Company makes no representations or warranties regarding suggestions or recommendations of services or products (including Content provided by publishers) offered or purchased through the Services. Products and services purchased or offered (whether or not following such recommendations and suggestions) the Services are provided “AS IS” without any warranty of any kind from Company or others unless, with respect to others (only), otherwise made expressly and unambiguously in writing by a designated third party for a specific product. THE SERVICES, CONTENT, WEBSITE AND ANY SOFTWARE ARE PROVIDED ON AN “AS IS” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>

<h2><b>REGISTRATION AND SECURITY</b></h2>

<p>As a condition to using Services, you may be required to register with Company and select a password and user name (“Company User ID”). You will provide Company with accurate, complete, and updated registration information. Failure to do so will constitute a breach of this Agreement, which may result in immediate termination of your account. You may not (i) select or use as a Company User ID a name of another person with the intent to impersonate that person; or (ii) use as a Company User ID a name subject to any rights of a person other than you without appropriate authorization. Company reserves the right to refuse registration of or cancel a Company User ID in its discretion. You will be responsible for maintaining the confidentiality of your password.</p>

<h2><b>INDEMNITY</b></h2>

<p>You will indemnify and hold Company, its parents, subsidiaries, affiliates, officers, and employees harmless (including, without limitation, from all damages, liabilities, settlements, costs and attorneys' fees) from any claim or demand made by any third party due to or arising out of your access to the Services, use or misuse of the Services, your violation of this Agreement (including any failure to obtain or provide any necessary consent and/or violation of applicable laws or regulations), or the infringement by you or any third party using your account of any intellectual property or other right of any person or entity, including your User Submissions.</p>

<h2><b>LIMITATION OF LIABILITY</b></h2>

<p>TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, IN NO EVENT WILL COMPANY OR ITS SUPPLIERS, OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE WITH RESPECT TO THE WEBSITE OR THE SERVICES OR THE SUBJECT MATTER OF THIS AGREEMENT UNDER ANY CONTRACT, NEGLIGENCE, TORT, STRICT LIABILITY OR OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY AMOUNT IN THE AGGREGATE IN EXCESS OF THE GREATER OF $100 OR THE FEES PAID BY YOU TO COMPANY HEREUNDER DURING THE 12-MONTH PERIOD PRECEDING THE APPLICABLE CLAIM; (II) FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER; (III) FOR DATA LOSS OR COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; (IV) FOR ANY INTERACTION WITH ANY THIRD PARTY THROUGH OR IN CONNECTION WITH THE SERVICE, INCLUDING OTHER USERS OR (IV) FOR ANY MATTER BEYOND COMPANY’S REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.
IN SUCH CASES, YOU AGREE THAT BECAUSE SUCH WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND COMPANY, AND ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND COMPANY, COMPANY’S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. YOU UNDERSTAND AND AGREE THAT COMPANY WOULD NOT BE ABLE TO OFFER THE SERVICE TO YOU ON AN ECONOMICALLY FEASIBLE BASIS WITHOUT THESE LIMITATIONS.</p>

<h2><b>CHANGE TO THE SERVICES</b></h2>

<p>The Company always tries to improve the Services, so they may change over time. The Company may suspend or discontinue any part of the Services, or introduce new features or impose limits on certain features or restrict access to parts or all of the Services. Company will try to provide you notice when we make a material change to the Services that would adversely affect you, but this may not always practical.</p>

<h2><b>FEES AND PAYMENT</b></h2>

<p>Access to and use of the Services is free, but in the future, we may offer new or additional special features which Company may charge for. Therefore, Company reserves the right to require payment of fees for certain Services. If you want access to those Services, you will pay all applicable fees for those Services, as will be described on the Services. If you continue to use those Services following such notification, that use constitutes your acceptance of any new or increased charges.</p>

<h2><b>THIRD PARTY WEBSITES</b></h2>

<p>The Services may contain links to third party websites that are not owned or controlled by Company, and includes features that allow you to interact and communicate with third parties. When you access third party websites, you do so at your own risk. Company encourages you to be aware when you leave the Website and to read the terms and conditions and privacy policy of each third party website that you visit. Company has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites. In addition, Company will not and cannot monitor, verify, censor or edit the content of any third party site. By using the Services, you expressly relieve and hold harmless Company from any and all liability arising from your use of any third party website or interaction or communication with any third party through or in connection with the Services. Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that Company will not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this site, or between users and any third party, you understand and agree that Company is under no obligation to become involved. IN THE EVENT THAT YOU HAVE A DISPUTE WITH ONE OR MORE OTHER USERS, YOU HEREBY RELEASE COMPANY, ITS OFFICERS, EMPLOYEES, AGENTS, AND SUCCESSORS IN RIGHTS FROM CLAIMS, DEMANDS, AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND OR NATURE, KNOWN OR UNKNOWN, SUSPECTED OR UNSUSPECTED, DISCLOSED OR UNDISCLOSED, ARISING OUT OF OR IN ANY WAY RELATED TO SUCH DISPUTES AND/OR OUR SERVICE. IF YOU ARE A CALIFORNIA RESIDENT, YOU SHALL AND HEREBY DO WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH SAYS: &quotA GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.&quot</p>

<h2><b>TERMINATION</b></h2>

<p>This Agreement will remain in full force and effect while you use the Services. You may terminate your use of the Services or your account at any time by contacting us at <a href="mailto:teachtogether1@gmail.com">teachtogether1@gmail.com.</a> Company may suspend or terminate your access to the Services, Website or your account at any time, for any reason (without cause or for your violation of any term of this Agreement), and without warning or notice, which may result in the forfeiture and destruction of all information associated with your membership. Upon termination of your account, your right to use the Services, access the Website, and any Content will immediately cease. All provisions of this Agreement which, by their nature, should survive termination, will survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability.</p>

<h2><b>CHOICE OF LAW AND ARBITRATION</b></h2>

<p>a) Generally. In the interest of resolving disputes between you and Company in the most expedient and cost effective manner, you and Company agree that any and all disputes arising in connection with this Agreement shall be resolved by binding arbitration. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Our agreement to arbitrate disputes includes, but is not limited to all claims arising out of or relating to any aspect of these Terms, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory, and regardless of whether the claims arise during or after the termination of these Terms. You understand and agree that, by entering into these Terms, you and Company are each waiving the right to a trial by jury or to participate in a class action.</p>

<p>b) Exceptions. Notwithstanding subsection (A), we both agree that nothing herein shall be deemed to waive, preclude, or otherwise limit either of our right to (i) bring an individual action in small claims court, (ii) pursue enforcement actions through applicable federal, state, or local agencies where such actions are available, (iii) seek injunctive relief in a court of law, or (iv) to file suit in a court of law to address intellectual property infringement claims.</p>

<p>c) Arbitrator. Any arbitration between you and Company will be governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, "AAA Rules") of the American Arbitration Association ("AAA"), as modified by these Terms, and will be administered by the AAA. The AAA Rules and filing forms are available online at www.adr.org, by calling the AAA at 1-800-778-7879, or by contacting Company.</p>

<p>d) Notice; Process. A party who intends to seek arbitration must first send a written notice of the dispute to the other, by certified mail or Federal Express (signature required), or in the event that we do not have a physical address on file for you, by electronic mail ("Notice"). Since Company currently do not have an applicable physical address, please send all such correspondences via electronic mail (“Notice”) to <a href="mailto:teachtogether1@gmail.com">teachtogether1@gmail.com</a> The Notice must (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought ("Demand"). We agree to use good faith efforts to resolve the claim directly, but If we do not reach an agreement to do so within 30 days after the Notice is received, you or Company may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by you or Company shall not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any; provided that if our dispute is finally resolved through arbitration in your favor, Company shall pay you the greater of (i) the amount awarded by the arbitrator, if any, and (ii) the greatest amount offered by Company in settlement of the dispute prior to the arbitrator’s award.</p>

<p>e) Fees. In the event that you commence arbitration in accordance with these Terms, Company will reimburse you for your payment of the filing fee, unless your claim is for greater than $10,000, in which case the payment of any fees shall be decided by the AAA Rules. Any arbitration hearings will take place at a location to be agreed upon in New York City, New York, provided that if the claim is for $10,000 or less, you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a non-appearance based telephonic hearing, or by an in-person hearing as established by the AAA Rules. If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In such case, you agree to reimburse Company for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceedings and upon request from either party made within 14 days of the arbitrator’s ruling on the merits.</p>

<p>f) No Class Actions. YOU AND COMPANY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Company agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding.</p>

<p>g) Modifications. In the event that Company makes any future change to this arbitration provision (other than a change to the Company's address for Notice), you may reject any such change by sending us electronic notice within 30 days of the change to <a href="mailto:teachtogether1@gmail.com">teachtogether1@gmail.com</a> for Notice, in which case your account with Company shall be immediately terminated and this arbitration provision, as in effect immediately prior to the amendments you reject shall survive. </p>

<p>h) Enforceability. If only Subsection F of this Section 13 or the entirety of this Section 13 is found to be unenforceable, then the entirety of this Section shall be null and void and, in such case, the parties agree that the exclusive jurisdiction and venue described elsewhere in Section 13 shall govern any action arising out of or related to these Terms.</p>

<h2><b>COPYRIGHT DISPUTE POLICY</b></h2>

<p>a) General. Company respects the rights of copyright owners and expects its users to do the same. Therefore, as required by the Terms, infringing content may not be submitted to the Service or used in, whole or in part, in any User Content.</p>

<p>b) User Content. If you upload User Content that contains any copyrighted work, including literary works, visual works, musical works, sound recordings, audiovisual works, or other work or any combination of the foregoing, then you must be the owner of such works or have all required rights, licenses, consents, and permissions to use such works on the Service and grant the rights granted herein. In addition to being grounds for removal of your User Content, termination of your account, and any other remedy Company may have against you, your failure to own or obtain such rights may subject you to civil and/or criminal liability, the damages for which can be significant.</p>

<p>c) Copyright Owner Rights. If you are a copyright owner or an agent thereof, and you believe any content submitted to and hosted on the Service infringes your copyrights, then you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing Company’s Designated Copyright Agent with the following information in writing:</p>

<p>(i) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>

<p>(ii) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Service are covered by a single notification, a representative list of such works on the Service;</p>

<p>(iii) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Company to locate the material;</p>

<p>(iv) information reasonably sufficient to permit Company to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;</p>

<p>(v) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law (for example, “I am under the good faith belief that the use of the copyrighted content that is identified herein is not authorized by the copyright owner, its agent, or the law.”); and</p>

<p>(vi) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed (for example, &quoI swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or authorized to act on behalf of the copyright owner, of the copyright(s) that is/are allegedly infringed by the aforementioned content.&quot).</p>

<p>Please consult your legal counsel (or see 17 U.S.C. § 512) to confirm these requirements and your compliance therewith. It is Company’s policy to respond to notices of alleged infringement that comply with the DMCA. In addition, Company will promptly terminate without notice the accounts of Users that are determined by Company to be “repeat infringers.” If Company receives more than three takedown notices regarding a User’s User Content, then that User will be considered a repeat infringer and their account will be terminated.</p>

<p>d) Designated Agent. All related correspondences can be sent to <a href="mailto:teachtogether1@gmail.com">teachtogether1@gmail.com.</a>  You acknowledge that if you fail to comply with all of the requirements of this section, your DMCA notice may not be valid. 
Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.</p>

<h2><b>DEVICE AND APPLICATION TERMS.</b></h2>

<p>These Terms apply to your use of all the Services, including the iPhone and iPad applications available via the Apple, Inc. (&quotApple&quot) App Store (the &quotApplication&quot) and the Android applications available via the Google, Inc. (&quotGoogle&quot) Play Store (the &quotApplication&quot), but additional terms also apply to the Application, which you can read here.</p>

<p>In the event you are using the Services in connection a Company application obtained through the Apple App Store or Google Play Store (collectively, such uses are henceforth the “Application”), the following will apply:</p>

<ul>
    <li>Both you and Company acknowledge that this Agreement is concluded between you and Company only, and not with Apple or Google, and that Apple or Google are not responsible for the Application or the Content;</li>
    <li>The Application is licensed to you on a limited, non-exclusive, non-transferrable, non-sublicensable basis, solely to be used in connection with the Service for your private, personal, non-commercial use, subject to all the terms and conditions of this Agreement as they are applicable to the Service;</li>
    <li>You will only use the Application in connection with a device that you own or control;</li>
    <li>In the event of any failure of the Application to conform to any applicable warranty, including those implied by law, you may notify Apple or Google of such failure; upon notification, Apple’s and Google’s sole warranty obligation to you will be to refund to you the purchase price, if any, of the Application;</li>
    <li>You acknowledge and agree that Company, and not Apple or Google, is responsible for addressing any claims you or any third party may have in relation to the Application;</li>
    <li>You acknowledge and agree that, in the event of any third party claim that the Application or your possession and use of the Application infringes that third party’s intellectual property rights, Company, and not Apple or Google, will be responsible for the investigation, defense, settlement and discharge of any such infringement claim;</li>
    <li>You represent and warrant that you are not located in a country subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country, and that you are not listed on any U.S. Government list of prohibited or restricted parties;</li>
    <li>Both you and Company acknowledge and agree that, in your use of the Application, you will comply with any applicable third party terms of agreement which may affect or be affected by such use; and</li>
    <li>Both you and Company acknowledge and agree that Apple and Apple’s subsidiaries and Google and Google’s subsidiaries are third party beneficiaries of this Agreement, and that upon your acceptance of this Agreement, Apple and Google will have the right (and will be deemed to have accepted the right) to enforce this Agreement against you as the third party beneficiary hereof.</li>
</ul>

<h2><b>MISCELLANEOUS</b></h2>

<p>The failure of either party to exercise, in any respect, any right provided for herein will not be deemed a waiver of any further rights hereunder. Company will not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond Company’s reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation (including “line-noise” interference). If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sub-licensable by you except with Company’s prior written consent. Company may transfer, assign or delegate this Agreement and its rights and obligations without consent. Both parties agree that this Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all modifications must be in a writing signed by both parties, except as otherwise provided herein. This Agreement and any subsequent versions of this Agreement posted to the Website and/or Services will be deemed a writing signed by both parties. No agency, partnership, joint venture, or employment is created as a result of this Agreement and you do not have any authority of any kind to bind Company in any way whatsoever.</p>

<p>Effective: May 7, 2015</p>
</section>
@stop
